import { notFound } from 'next/navigation'
import QRCode from 'qrcode'
import { getReviewPageData, reviewLinkFor } from '@/lib/reviews/google'

// Public, shareable, no login — clients hand this URL to customers.
export const dynamic = 'force-dynamic'

export async function generateMetadata({ params }: { params: { slug: string } }) {
  // Title and description need only the name and the publish flag, so this skips
  // the Places call the page body makes.
  const data = await getReviewPageData(params.slug, { withReviews: false })
  // Same withholding as the page body — metadata must not name a client whose
  // page is not published.
  if (!data || !data.enabled) return { title: 'Reviews' }
  return {
    title: `${data.businessName} — Reviews`,
    description: `Read reviews for ${data.businessName} and leave your own.`,
  }
}

function Stars({ rating, color }: { rating: number; color: string }) {
  const full = Math.round(rating)
  return (
    <span aria-label={`${rating} out of 5`} style={{ color, letterSpacing: 1 }}>
      {'★'.repeat(Math.max(0, Math.min(5, full)))}
      <span style={{ opacity: 0.25 }}>{'★'.repeat(Math.max(0, 5 - full))}</span>
    </span>
  )
}

export default async function ReviewsPage({ params }: { params: { slug: string } }) {
  const data = await getReviewPageData(params.slug)
  if (!data) notFound()

  // The publish switch has to actually withhold the page, otherwise every
  // client has a live public URL the moment they exist. 404 rather than a
  // "not published" notice, so the URL reveals nothing before it is ready.
  if (!data.enabled) notFound()

  const brand = data.brandColor
  const link = data.placeId ? reviewLinkFor(data.placeId) : null

  // Inline SVG so the page needs no client JS and no extra request.
  let qrSvg: string | null = null
  if (link) {
    try {
      qrSvg = await QRCode.toString(link, {
        type: 'svg',
        margin: 1,
        errorCorrectionLevel: 'M',
        color: { dark: /^#[0-9a-fA-F]{6}$/.test(brand) ? brand : '#111111', light: '#FFFFFF' },
      })
    } catch {
      qrSvg = null
    }
  }

  return (
    <div style={{ minHeight: '100vh', background: '#fafaf8' }}>
      <div style={{ background: brand, color: 'white', padding: '28px 20px' }}>
        <div style={{ maxWidth: 720, margin: '0 auto' }}>
          <h1 style={{ margin: 0, fontSize: 26, fontWeight: 700, lineHeight: 1.2 }}>
            {data.businessName}
          </h1>
          {data.rating != null && (
            <p style={{ margin: '8px 0 0', fontSize: 15, opacity: 0.95 }}>
              {data.rating.toFixed(1)} out of 5
              {data.totalRatings != null && ` · ${data.totalRatings.toLocaleString()} Google reviews`}
            </p>
          )}
        </div>
      </div>

      <main style={{ maxWidth: 720, margin: '0 auto', padding: '24px 20px 56px' }}>
        {/* Leave a review — the point of the page */}
        {link && (
          <section
            style={{
              background: 'white', border: '1px solid #e7e5e4', borderRadius: 14,
              padding: 20, textAlign: 'center',
            }}
          >
            <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: '#111' }}>
              Scan to Leave a Review
            </h2>
            <p style={{ margin: '6px 0 16px', fontSize: 13, color: '#666' }}>
              Point your phone camera at the code, or tap the button below. It takes about 30 seconds.
            </p>

            {qrSvg && (
              <div
                style={{ width: 200, height: 200, margin: '0 auto 16px' }}
                // Generated by the qrcode package from our own URL — no user input.
                dangerouslySetInnerHTML={{ __html: qrSvg }}
              />
            )}

            <a
              href={link}
              target="_blank"
              rel="noreferrer"
              style={{
                display: 'inline-block', background: brand, color: 'white',
                padding: '12px 24px', borderRadius: 10, fontWeight: 700,
                textDecoration: 'none', fontSize: 15,
              }}
            >
              Write a Google review
            </a>

            <div style={{ marginTop: 12 }}>
              <a
                href={`/reviews/${data.clientId}/qr`}
                style={{ fontSize: 12, color: '#666' }}
              >
                Download QR code (PNG) for print
              </a>
            </div>
          </section>
        )}

        {!data.placeId && (
          <section
            style={{
              background: 'white', border: '1px solid #e7e5e4', borderRadius: 14,
              padding: 20, textAlign: 'center', color: '#666', fontSize: 14,
            }}
          >
            Reviews aren&apos;t set up for {data.businessName} yet.
          </section>
        )}

        {/* Existing reviews */}
        {data.reviews.length > 0 && (
          <section style={{ marginTop: 28 }}>
            <h2 style={{ fontSize: 15, fontWeight: 700, color: '#111', margin: '0 0 12px' }}>
              What customers say
            </h2>
            <div style={{ display: 'grid', gap: 12 }}>
              {data.reviews.map((r, i) => (
                <article
                  key={i}
                  style={{
                    background: 'white', border: '1px solid #e7e5e4',
                    borderRadius: 12, padding: 16,
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                    <div style={{ fontWeight: 600, fontSize: 14, color: '#111' }}>
                      {r.author_name}
                    </div>
                    <span style={{ marginLeft: 'auto', fontSize: 12, color: '#888' }}>
                      {r.relative_time_description}
                    </span>
                  </div>
                  <div style={{ fontSize: 14, marginBottom: 6 }}>
                    <Stars rating={r.rating} color={brand} />
                  </div>
                  {r.text && (
                    <p style={{ margin: 0, fontSize: 14, lineHeight: 1.6, color: '#333', whiteSpace: 'pre-wrap' }}>
                      {r.text}
                    </p>
                  )}
                </article>
              ))}
            </div>
            <p style={{ fontSize: 11, color: '#999', marginTop: 12 }}>
              Reviews shown are the most recent supplied by Google, which returns up to five.
            </p>
          </section>
        )}

        {data.placeId && data.reviews.length === 0 && (
          <p style={{ marginTop: 24, fontSize: 13, color: '#666', textAlign: 'center' }}>
            {data.fetchError
              ? 'Reviews are temporarily unavailable.'
              : 'No Google reviews yet — be the first.'}
          </p>
        )}

        <footer style={{ marginTop: 40, textAlign: 'center', fontSize: 11, color: '#aaa' }}>
          Powered by A&amp;B Consulting Group
        </footer>
      </main>
    </div>
  )
}
